Don't kill old master process. Allow unicorn to either upgrade or revert it

diff --git a/lib/generators/capistrano/unicorn_nginx/templates/unicorn_init.erb b/lib/generators/capistrano/unicorn_nginx/templates/unicorn_init.erb
--- a/lib/generators/capistrano/unicorn_nginx/templates/unicorn_init.erb
+++ b/lib/generators/capistrano/unicorn_nginx/templates/unicorn_init.erb
@@ -27,10 +27,6 @@ sig () {
   test -s "$PID" && kill -$1 `cat $PID`
 }
 
-oldsig () {
-  test -s $OLD_PIN && kill -$1 `cat $OLD_PIN`
-}
-
 run () {
   if [ "$(id -un)" = "$AS_USER" ]; then
     eval $1
@@ -58,8 +54,14 @@ restart|reload)
   run "$CMD"
   ;;
 upgrade)
-  if sig USR2 && sleep 2 && sig 0 && oldsig QUIT
+  current_master=`cat $PID`
+  if sig USR2 && sleep 20 && sig 0
   then
+    if test $current_master -eq `cat $PID`
+    then
+      echo >&2 "Failed to upgrade, reverted to old master. Check stderr log for details"
+      exit 1
+    fi
     n=$TIMEOUT
     while test -s $OLD_PIN && test $n -ge 0
     do
